import { Metadata } from "next";

export const metadata: Metadata = {
  title: "About ViewCastLK",
  description: "Learn about the architecture, development status, and team behind the ViewCastLK project.",
};

export default function AboutPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-10 space-y-12">
      {/* 1. Hero Section */}
      <section className="text-center space-y-4">
        <h1 className="text-3xl font-bold text-white tracking-tight sm:text-4xl">
          About ViewCastLK
        </h1>
        <p className="text-lg text-slate-300 leading-relaxed max-w-3xl mx-auto">
          ViewCastLK is a pre-publication YouTube view forecasting system designed
          for verified Sri Lankan channels. It estimates a planned video&apos;s total
          views at 7, 14, 21, and 30 days after publication using information
          available before the video is uploaded.
        </p>
      </section>

      {/* 2. Problem Section */}
      <section className="bg-slate-800/30 rounded-2xl border border-slate-700 p-6 sm:p-8">
        <h2 className="text-xl font-semibold text-slate-100 mb-3">The Problem</h2>
        <p className="text-slate-400 leading-relaxed">
          Content creators usually depend on intuition or post-publication early
          engagement metrics (such as views in the first 24 hours) when
          estimating a new video&apos;s performance. ViewCastLK aims to provide an
          earlier, data-driven estimate using only planned video metadata and
          historical channel information.
        </p>
      </section>

      {/* 3. How it works */}
      <section>
        <h2 className="text-xl font-semibold text-slate-100 mb-5">How it works</h2>
        <div className="grid sm:grid-cols-2 gap-4">
          {[
            "Verified Sri Lankan channel data collection",
            "Historical metadata and snapshot preparation",
            "Machine-learning forecasting",
            "Dashboard presentation across four forecast horizons",
          ].map((step, idx) => (
            <div
              key={idx}
              className="flex items-start gap-3 bg-slate-800/40 rounded-xl p-4 border border-slate-700/50"
            >
              <div className="flex-shrink-0 w-6 h-6 rounded-full bg-blue-500/20 text-blue-400 flex items-center justify-center text-xs font-bold ring-1 ring-blue-500/50">
                {idx + 1}
              </div>
              <p className="text-slate-300 text-sm font-medium pt-0.5">{step}</p>
            </div>
          ))}
        </div>
      </section>

      {/* 4. Forecast horizons */}
      <section>
        <h2 className="text-xl font-semibold text-slate-100 mb-2">
          Forecast Horizons
        </h2>
        <p className="text-sm text-slate-400 mb-5">
          The values generated by the model represent predicted total views at
          each of these time horizons.
        </p>
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
          {[7, 14, 21, 30].map((day) => (
            <div
              key={day}
              className="bg-slate-800/50 border border-slate-700 rounded-xl p-4 text-center"
            >
              <span className="block text-xs text-slate-500 uppercase tracking-wider font-semibold mb-1">
                Day
              </span>
              <span className="text-2xl font-bold text-blue-400">{day}</span>
            </div>
          ))}
        </div>
      </section>

      {/* 5. Data collection */}
      <section className="bg-slate-800/30 rounded-2xl border border-slate-700 p-6 sm:p-8">
        <h2 className="text-xl font-semibold text-slate-100 mb-4">
          Data Collection
        </h2>
        <ul className="space-y-3 text-slate-400 text-sm leading-relaxed list-disc list-inside marker:text-slate-600">
          <li>Leverages the YouTube Data API for data retrieval.</li>
          <li>Utilizes channel-roster-based collection.</li>
          <li>
            Channels are verified using the declared country code{" "}
            <strong className="text-slate-300 font-medium">LK</strong>.
          </li>
          <li>Upload discovery is achieved through channel upload playlists.</li>
          <li>
            Video and channel statistics are collected at regular intervals to
            form historical snapshots.
          </li>
          <li>Data is securely stored using PostgreSQL through Supabase.</li>
        </ul>
      </section>

      {/* 6. System architecture */}
      <section>
        <h2 className="text-xl font-semibold text-slate-100 mb-5">
          System Architecture
        </h2>
        <div className="flex flex-wrap items-center justify-center gap-2 text-sm">
          {[
            "YouTube Data API",
            "Data Collection",
            "Supabase PostgreSQL",
            "Feature Engineering and ML Model",
            "Prediction API",
            "Next.js Dashboard",
          ].map((component, idx, arr) => (
            <div key={component} className="flex items-center gap-2">
              <span className="bg-slate-800 border border-slate-700 px-3 py-1.5 rounded-lg text-slate-300 font-medium text-center">
                {component}
              </span>
              {idx < arr.length - 1 && (
                <span className="text-slate-500" aria-hidden="true">
                  →
                </span>
              )}
            </div>
          ))}
        </div>
      </section>

      {/* 7. Current development status */}
      <section className="bg-slate-800/30 rounded-2xl border border-slate-700 p-6 sm:p-8">
        <h2 className="text-xl font-semibold text-slate-100 mb-4">
          Current Development Status
        </h2>
        <ul className="space-y-2 text-slate-400 text-sm">
          <li className="flex items-center gap-2">
            <span className="text-emerald-500">✓</span> Dashboard UI is
            implemented
          </li>
          <li className="flex items-center gap-2">
            <span className="text-amber-500">⚠</span> Forecast results currently
            use illustrative mock data
          </li>
          <li className="flex items-center gap-2">
            <span className="text-amber-500">⚠</span> Prediction API integration
            is planned
          </li>
          <li className="flex items-center gap-2">
            <span className="text-amber-500">⚠</span> Final model evaluation
            metrics are not yet available
          </li>
          <li className="flex items-center gap-2">
            <span className="text-amber-500">⚠</span> Model selection is still
            under evaluation
          </li>
        </ul>
      </section>

      {/* 8. Project scope and novelty */}
      <section>
        <h2 className="text-xl font-semibold text-slate-100 mb-3">
          Project Scope & Novelty
        </h2>
        <div className="grid sm:grid-cols-2 gap-4">
          <div className="bg-slate-800/50 rounded-xl p-4 border border-slate-700">
            <h3 className="text-slate-200 font-medium mb-1">
              Pre-publication Forecasting
            </h3>
            <p className="text-sm text-slate-400">
              Forecasting occurs entirely before publication. Early engagement
              metrics are not required to generate predictions.
            </p>
          </div>
          <div className="bg-slate-800/50 rounded-xl p-4 border border-slate-700">
            <h3 className="text-slate-200 font-medium mb-1">
              Multiple Horizons
            </h3>
            <p className="text-sm text-slate-400">
              Four distinct forecast horizons are provided (Days 7, 14, 21, and
              30) rather than a single point estimate.
            </p>
          </div>
          <div className="bg-slate-800/50 rounded-xl p-4 border border-slate-700 sm:col-span-2">
            <h3 className="text-slate-200 font-medium mb-1">
              Localized Context
            </h3>
            <p className="text-sm text-slate-400">
              The project specifically focuses on verified Sri Lankan YouTube
              channels to model local creator dynamics.
            </p>
          </div>
        </div>
      </section>

      {/* 9. Team responsibilities */}
      <section>
        <h2 className="text-xl font-semibold text-slate-100 mb-5">
          Team Responsibilities
        </h2>
        <div className="grid md:grid-cols-3 gap-4">
          {/* M.J.S. */}
          <div className="bg-slate-800/30 rounded-2xl border border-slate-700 p-5">
            <div className="mb-3">
              <h3 className="text-slate-100 font-semibold text-lg">M.J.S.</h3>
              <p className="text-slate-500 text-xs font-medium">230023E</p>
            </div>
            <p className="text-sm text-slate-400 leading-relaxed">
              Data collector, database, automation, prediction API, deployment,
              data cleaning, exploratory analysis, and testing documentation.
            </p>
          </div>

          {/* M.U.A. */}
          <div className="bg-slate-800/30 rounded-2xl border border-slate-700 p-5">
            <div className="mb-3">
              <h3 className="text-slate-100 font-semibold text-lg">M.U.A.</h3>
              <p className="text-slate-500 text-xs font-medium">230025L</p>
            </div>
            <p className="text-sm text-slate-400 leading-relaxed">
              Dashboard frontend, wireframes, database backup, software
              architecture documentation, usability validation, and final report.
            </p>
          </div>

          {/* M.R.R. */}
          <div className="bg-slate-800/30 rounded-2xl border border-slate-700 p-5">
            <div className="mb-3">
              <h3 className="text-slate-100 font-semibold text-lg">M.R.R.</h3>
              <p className="text-slate-500 text-xs font-medium">230027U</p>
            </div>
            <p className="text-sm text-slate-400 leading-relaxed">
              Feasibility study, software requirements specification, feature
              engineering, model training and evaluation, model export,
              visualizations, and demonstration video.
            </p>
          </div>
        </div>
      </section>

      {/* 10. Academic notice */}
      <section className="pt-6 border-t border-slate-800 text-center">
        <p className="text-xs text-slate-500">
          <strong>Academic Notice:</strong> ViewCastLK is a university academic
          project and is not affiliated with or endorsed by YouTube or Google.
        </p>
      </section>
    </div>
  );
}
